# Generated by Django 4.1.3 on 2023-04-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_recommendation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprocedure',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Notificado'),
        ),
    ]
